#!/bin/bash

set -v on

cd Codefield/X02_Lite/utils

lcm-gen -x vr_lcm_recv.lcm --cpp-hpath ../include

cd ..

mkdir build

cd build

cmake .. 
# -DCMAKE_PREFIX_PATH=/opt/openrobots

make

#cp -r /usr/local ~/temp